language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    - build-tools-29.0.3

    - android-29

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-29
    - sys-img-armeabi-v7a-android-17
before_install: 
    - cd LinkingYou
    - chmod +x gradlew
script:
  - ./gradlew assembleRelease --stacktrace
