language: android
dist: trusty
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra

licenses:
  - '.+'
